#!/bin/sh
echo ""

#m1="E4956E4000ff"
m1="E4:95:6E:40:00:ff"
m1="70:3a:cb:79:b9:06"
echo "m1 = $m1"

m2=$( echo "$m1" | tr -d ':' )
echo "m2 = $m2"

m3=$( echo $((16#${m2})) )
echo "m3 = $m3"

m4=$( echo $((16#${m2}+1)) )
echo "m4 = $m4"

m5=$( echo "obase=16;${m3}"|bc )
echo "m5 = $m5"

mac=$( echo "obase=16;${m4}"|bc )
echo "m6 = $mac"


real_mac="\x${mac:0:2}\x${mac:2:2}\x${mac:4:2}\x${mac:6:2}\x${mac:8:2}\x${mac:10:2}"
printf "$real_mac" |dd of=./file.bin bs=1 count=6 seek=0 conv=notrunc 2>/dev/null

#a=$( printf "%.2x\n" $(echo $((16#$MAC+1))) )
#echo $a

eth0=$( echo "$m1" | tr -d ':' )
tmp1=$((16#${eth0}+4))
eth1=$( echo "obase=16;${tmp1}"|bc)
echo "eth1 $eth1"

echo ""